name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build
        run: node build.js
        env:
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}

      - name: Commit generated config file if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add config.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "Build: update config.js" && git push)
